/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class FDKCodec */

#ifndef _Included_fdkaac_FDKCodec
#define _Included_fdkaac_FDKCodec

#include <jni.h>
#include <string>
#include "aacenc_lib.h"
#include <android/log.h>
#include <aacdecoder_lib.h>

#define  LOG_TAG    "fdkcodec"
#define  LOGD(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_example_fdkaactest_fdkaac_FDKCodec_initEncoder
        (JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT jbyteArray JNICALL Java_com_example_fdkaactest_fdkaac_FDKCodec_encode
        (JNIEnv *, jobject, jshortArray,jint len);

JNIEXPORT void JNICALL Java_com_example_fdkaactest_fdkaac_FDKCodec_releaseEncoder
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_fdkaactest_fdkaac_FDKCodec_initDecoder
        (JNIEnv *, jobject);


JNIEXPORT jbyteArray JNICALL Java_com_example_fdkaactest_fdkaac_FDKCodec_decode
        (JNIEnv *, jobject, jbyteArray);


JNIEXPORT void JNICALL Java_com_example_fdkaactest_fdkaac_FDKCodec_releaseDecoder
        (JNIEnv *, jobject);

#ifdef __cplusplus
}

#endif
#endif